#!/bin/bash

if [ $(id -u) != 0 ]; then
  echo "You ain't root."
  exit 1
fi

if [ $# = 0 ]; then
  echo "Usage: $0 path"
  exit 1
fi

user=brandanl
group=100

for path in "$@"; do
  for file in $(find $path \( -type f -o -type d \) -user brandan | grep -v '.svn' | grep -v '/.git'); do
    chown $user:$group "$file"
    chmod g+w "$file"
  done
done
