#!/bin/bash

local=`git show-branch | cut -f2- -d\ `
remote=`git show-branch -r | cut -f2- -d\ `

if [ "x$local" != "x$remote" ]; then
  echo -n "You probably need to 'git push'. Continue anyway? [n] "
  read reply
  
  if [ "x${reply:0:1}" != "xy" ]; then
    exit 1
  fi
fi
