#!/usr/bin/env ruby

# Save this somewhere, chmod 755 it, then add
#   complete -C path/to/this/script -o default git
# to your ~/.bashrc
#
# Adapted from 
# http://onrails.org/articles/2006/08/30/namespaces-and-rake-command-completion

exit 0 unless /^git\b/ =~ ENV['COMP_LINE']

commands = %w{
  add
  bisect
  branch
  checkout
  clone
  commit
  diff
  fetch
  grep
  init
  log
  merge
  mv
  pull
  push
  rebase
  reset
  rm
  show
  status
  tag
}

after_match = $'
task_match = (after_match.empty? || after_match =~ /\s$/) ? nil : after_match.split.last
commands = commands.select { |t| /^#{Regexp.escape task_match}/ =~ t } if task_match

puts commands
exit 0
