#!/usr/bin/env ruby

if ARGV.length != 2
  puts "Usage: #{$0} userish hostish"
  exit 1
end

require 'json'

user = ARGV.shift
host = ARGV.shift

config = JSON.parse(File.read(File.join(ENV['HOME'], '.quick_ssh')))

usernames = config['usernames']
hostnames = config['hostnames']
domain = config['domain']

usernames.default = usernames['default']
hostnames.default = host

real_host = hostnames[host]
real_user = usernames[real_host]

command = "ssh #{real_user}@#{real_host}.#{domain}"

puts command
exec command
