#!/bin/bash

if [ $# -lt 1 ]; then
  echo "Usage: $0 /path/to/repo [host] [remote_path]"
  exit 1
fi

. ~/.bash_functions

local_path=$1

if [ "x$2" = "x" ]; then
  host=192.168.42.140
else
  host=$2
fi

if [ "x$3" = "x" ]; then
  remote_path=/tmp
else
  remote_path=$3
fi

echzec "rsync -rlcvz --exclude-from=$HOME/.sync-repo-excludes $local_path brandanl@$host:$remote_path"
